# Generated by Django 4.2 on 2023-04-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_delete_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.IntegerField(),
        ),
    ]
